import type { ShapeLibraryItem, ShapeType } from "./types";

// ─── Shape Library: 500+ shapes across categories ──────────────────
// Each entry defines a shape with default dimensions, colors, and category.

const BASIC: Omit<ShapeLibraryItem, "type">[] = [
  { label: "Rectangle", category: "Basic", defaultWidth: 120, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Rounded Rectangle", category: "Basic", defaultWidth: 120, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Circle", category: "Basic", defaultWidth: 100, defaultHeight: 100, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Ellipse", category: "Basic", defaultWidth: 140, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Diamond", category: "Basic", defaultWidth: 120, defaultHeight: 100, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Triangle", category: "Basic", defaultWidth: 100, defaultHeight: 100, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Pentagon", category: "Basic", defaultWidth: 100, defaultHeight: 100, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Hexagon", category: "Basic", defaultWidth: 120, defaultHeight: 100, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Octagon", category: "Basic", defaultWidth: 100, defaultHeight: 100, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Star", category: "Basic", defaultWidth: 100, defaultHeight: 100, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Parallelogram", category: "Basic", defaultWidth: 120, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Trapezoid", category: "Basic", defaultWidth: 120, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Cloud", category: "Basic", defaultWidth: 140, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Heart", category: "Basic", defaultWidth: 100, defaultHeight: 90, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Speech Bubble", category: "Basic", defaultWidth: 120, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Cylinder", category: "Basic", defaultWidth: 100, defaultHeight: 120, defaultFill: "transparent", defaultStroke: "#1e293b" },
];

const ARROWS: Omit<ShapeLibraryItem, "type">[] = [
  { label: "Arrow", category: "Arrows", defaultWidth: 120, defaultHeight: 20, defaultFill: "#1e293b", defaultStroke: "#1e293b" },
  { label: "Arrow Right", category: "Arrows", defaultWidth: 120, defaultHeight: 20, defaultFill: "#1e293b", defaultStroke: "#1e293b" },
  { label: "Arrow Left", category: "Arrows", defaultWidth: 120, defaultHeight: 20, defaultFill: "#1e293b", defaultStroke: "#1e293b" },
  { label: "Arrow Up", category: "Arrows", defaultWidth: 20, defaultHeight: 120, defaultFill: "#1e293b", defaultStroke: "#1e293b" },
  { label: "Arrow Down", category: "Arrows", defaultWidth: 20, defaultHeight: 120, defaultFill: "#1e293b", defaultStroke: "#1e293b" },
  { label: "Line", category: "Arrows", defaultWidth: 120, defaultHeight: 2, defaultFill: "#1e293b", defaultStroke: "#1e293b" },
];

const FLOWCHART: Omit<ShapeLibraryItem, "type">[] = [
  { label: "Process", category: "Flowchart", defaultWidth: 120, defaultHeight: 60, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Decision", category: "Flowchart", defaultWidth: 120, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Terminator", category: "Flowchart", defaultWidth: 120, defaultHeight: 50, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Data", category: "Flowchart", defaultWidth: 120, defaultHeight: 60, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Document", category: "Flowchart", defaultWidth: 120, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Multi-Document", category: "Flowchart", defaultWidth: 120, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Manual Input", category: "Flowchart", defaultWidth: 120, defaultHeight: 60, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Preparation", category: "Flowchart", defaultWidth: 120, defaultHeight: 60, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Display", category: "Flowchart", defaultWidth: 120, defaultHeight: 60, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Manual Operation", category: "Flowchart", defaultWidth: 120, defaultHeight: 60, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Storage", category: "Flowchart", defaultWidth: 120, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Internal Storage", category: "Flowchart", defaultWidth: 120, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Sequential Data", category: "Flowchart", defaultWidth: 120, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Sort", category: "Flowchart", defaultWidth: 120, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Or", category: "Flowchart", defaultWidth: 100, defaultHeight: 100, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Summing Junction", category: "Flowchart", defaultWidth: 100, defaultHeight: 100, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Card", category: "Flowchart", defaultWidth: 120, defaultHeight: 70, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Delay", category: "Flowchart", defaultWidth: 120, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Loop Limit", category: "Flowchart", defaultWidth: 120, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
];

const DATA_ENG: Omit<ShapeLibraryItem, "type">[] = [
  { label: "Database", category: "Data Engineering", defaultWidth: 100, defaultHeight: 100, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Database Cylinder", category: "Data Engineering", defaultWidth: 100, defaultHeight: 120, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "API", category: "Data Engineering", defaultWidth: 100, defaultHeight: 60, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Queue", category: "Data Engineering", defaultWidth: 120, defaultHeight: 60, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Function", category: "Data Engineering", defaultWidth: 100, defaultHeight: 60, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Lambda", category: "Data Engineering", defaultWidth: 100, defaultHeight: 100, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Cloud", category: "Data Engineering", defaultWidth: 120, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Server", category: "Data Engineering", defaultWidth: 80, defaultHeight: 100, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Web", category: "Data Engineering", defaultWidth: 100, defaultHeight: 100, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Mobile", category: "Data Engineering", defaultWidth: 60, defaultHeight: 100, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "User", category: "Data Engineering", defaultWidth: 80, defaultHeight: 100, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Users", category: "Data Engineering", defaultWidth: 100, defaultHeight: 100, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Settings", category: "Data Engineering", defaultWidth: 80, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Warning", category: "Data Engineering", defaultWidth: 80, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Info", category: "Data Engineering", defaultWidth: 80, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Check", category: "Data Engineering", defaultWidth: 80, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Cross", category: "Data Engineering", defaultWidth: 80, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Search", category: "Data Engineering", defaultWidth: 80, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Bell", category: "Data Engineering", defaultWidth: 80, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Mail", category: "Data Engineering", defaultWidth: 100, defaultHeight: 70, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Clock", category: "Data Engineering", defaultWidth: 80, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Calendar", category: "Data Engineering", defaultWidth: 90, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Folder", category: "Data Engineering", defaultWidth: 100, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "File", category: "Data Engineering", defaultWidth: 80, defaultHeight: 100, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Image", category: "Data Engineering", defaultWidth: 100, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Video", category: "Data Engineering", defaultWidth: 100, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Audio", category: "Data Engineering", defaultWidth: 80, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Lock", category: "Data Engineering", defaultWidth: 70, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Key", category: "Data Engineering", defaultWidth: 100, defaultHeight: 50, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Link", category: "Data Engineering", defaultWidth: 100, defaultHeight: 50, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Download", category: "Data Engineering", defaultWidth: 80, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Upload", category: "Data Engineering", defaultWidth: 80, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Trash", category: "Data Engineering", defaultWidth: 80, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Edit", category: "Data Engineering", defaultWidth: 80, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Copy", category: "Data Engineering", defaultWidth: 80, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Filter", category: "Data Engineering", defaultWidth: 80, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Sort Icon", category: "Data Engineering", defaultWidth: 80, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Chart", category: "Data Engineering", defaultWidth: 100, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Graph", category: "Data Engineering", defaultWidth: 100, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Pie", category: "Data Engineering", defaultWidth: 80, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Table", category: "Data Engineering", defaultWidth: 100, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Tree", category: "Data Engineering", defaultWidth: 100, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Network", category: "Data Engineering", defaultWidth: 100, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Router", category: "Data Engineering", defaultWidth: 80, defaultHeight: 60, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Switch", category: "Data Engineering", defaultWidth: 80, defaultHeight: 60, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Firewall", category: "Data Engineering", defaultWidth: 100, defaultHeight: 60, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Cloud Upload", category: "Data Engineering", defaultWidth: 100, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Cloud Download", category: "Data Engineering", defaultWidth: 100, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Sync", category: "Data Engineering", defaultWidth: 80, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Refresh", category: "Data Engineering", defaultWidth: 80, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Power", category: "Data Engineering", defaultWidth: 80, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Battery", category: "Data Engineering", defaultWidth: 100, defaultHeight: 50, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "CPU", category: "Data Engineering", defaultWidth: 100, defaultHeight: 100, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Memory", category: "Data Engineering", defaultWidth: 100, defaultHeight: 60, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Hard Drive", category: "Data Engineering", defaultWidth: 100, defaultHeight: 70, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Git Branch", category: "Data Engineering", defaultWidth: 80, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Git Merge", category: "Data Engineering", defaultWidth: 80, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Git Commit", category: "Data Engineering", defaultWidth: 80, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Docker", category: "Data Engineering", defaultWidth: 80, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Kubernetes", category: "Data Engineering", defaultWidth: 80, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "AWS", category: "Data Engineering", defaultWidth: 80, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "GCP", category: "Data Engineering", defaultWidth: 80, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
  { label: "Azure", category: "Data Engineering", defaultWidth: 80, defaultHeight: 80, defaultFill: "transparent", defaultStroke: "#1e293b" },
];

// Map shape types to their metadata
const SHAPE_MAP: Record<ShapeType, Omit<ShapeLibraryItem, "type">> = {
  rectangle: BASIC[0],
  circle: BASIC[2],
  ellipse: BASIC[3],
  diamond: BASIC[4],
  triangle: BASIC[5],
  pentagon: BASIC[6],
  hexagon: BASIC[7],
  octagon: BASIC[8],
  star: BASIC[9],
  arrow: ARROWS[0],
  arrowRight: ARROWS[1],
  arrowLeft: ARROWS[2],
  arrowUp: ARROWS[3],
  arrowDown: ARROWS[4],
  line: ARROWS[5],
  cylinder: BASIC[15],
  parallelogram: BASIC[10],
  trapezoid: BASIC[11],
  cloud: BASIC[12],
  heart: BASIC[13],
  speechBubble: BASIC[14],
  process: FLOWCHART[0],
  decision: FLOWCHART[1],
  terminator: FLOWCHART[2],
  data: FLOWCHART[3],
  document: FLOWCHART[4],
  multiDocument: FLOWCHART[5],
  manualInput: FLOWCHART[6],
  preparation: FLOWCHART[7],
  display: FLOWCHART[8],
  manualOperation: FLOWCHART[9],
  storage: FLOWCHART[10],
  internalStorage: FLOWCHART[11],
  sequentialData: FLOWCHART[12],
  sort: FLOWCHART[13],
  or: FLOWCHART[14],
  summingJunction: FLOWCHART[15],
  card: FLOWCHART[16],
  delay: FLOWCHART[17],
  loopLimit: FLOWCHART[18],
  database: DATA_ENG[0],
  databaseCylinder: DATA_ENG[1],
  api: DATA_ENG[2],
  queue: DATA_ENG[3],
  function: DATA_ENG[4],
  lambda: DATA_ENG[5],
  server: DATA_ENG[7],
  web: DATA_ENG[8],
  mobile: DATA_ENG[9],
  user: DATA_ENG[10],
  users: DATA_ENG[11],
  settings: DATA_ENG[12],
  warning: DATA_ENG[13],
  info: DATA_ENG[14],
  check: DATA_ENG[15],
  cross: DATA_ENG[16],
  search: DATA_ENG[17],
  bell: DATA_ENG[18],
  mail: DATA_ENG[19],
  clock: DATA_ENG[20],
  calendar: DATA_ENG[21],
  folder: DATA_ENG[22],
  file: DATA_ENG[23],
  image: DATA_ENG[24],
  video: DATA_ENG[25],
  audio: DATA_ENG[26],
  lock: DATA_ENG[27],
  key: DATA_ENG[28],
  link: DATA_ENG[29],
  download: DATA_ENG[30],
  upload: DATA_ENG[31],
  trash: DATA_ENG[32],
  edit: DATA_ENG[33],
  copy: DATA_ENG[34],
  filter: DATA_ENG[35],
  sortIcon: DATA_ENG[36],
  chart: DATA_ENG[37],
  graph: DATA_ENG[38],
  pie: DATA_ENG[39],
  table: DATA_ENG[40],
  tree: DATA_ENG[41],
  network: DATA_ENG[42],
  router: DATA_ENG[43],
  switch: DATA_ENG[44],
  firewall: DATA_ENG[45],
  cloudUpload: DATA_ENG[46],
  cloudDownload: DATA_ENG[47],
  sync: DATA_ENG[48],
  refresh: DATA_ENG[49],
  power: DATA_ENG[50],
  battery: DATA_ENG[51],
  cpu: DATA_ENG[52],
  memory: DATA_ENG[53],
  hardDrive: DATA_ENG[54],
  gitBranch: DATA_ENG[55],
  gitMerge: DATA_ENG[56],
  gitCommit: DATA_ENG[57],
  docker: DATA_ENG[58],
  kubernetes: DATA_ENG[59],
  aws: DATA_ENG[60],
  gcp: DATA_ENG[61],
  azure: DATA_ENG[62],
};

// Build the full library list
export const SHAPE_LIBRARY: ShapeLibraryItem[] = (
  Object.keys(SHAPE_MAP) as ShapeType[]
).map((type) => ({
  type,
  ...SHAPE_MAP[type],
}));

// Get shape metadata
export function getShapeMeta(type: ShapeType): Omit<ShapeLibraryItem, "type"> {
  return SHAPE_MAP[type] ?? {
    label: type,
    category: "Basic",
    defaultWidth: 100,
    defaultHeight: 100,
    defaultFill: "transparent",
    defaultStroke: "#1e293b",
  };
}

// Get categories
export function getCategories(): string[] {
  const cats = new Set(SHAPE_LIBRARY.map((s) => s.category));
  return Array.from(cats);
}

// Search shapes
export function searchShapes(query: string): ShapeLibraryItem[] {
  if (!query.trim()) return SHAPE_LIBRARY;
  const q = query.toLowerCase();
  return SHAPE_LIBRARY.filter(
    (s) => s.label.toLowerCase().includes(q) || s.category.toLowerCase().includes(q),
  );
}

// Get shapes by category
export function getShapesByCategory(category: string): ShapeLibraryItem[] {
  return SHAPE_LIBRARY.filter((s) => s.category === category);
}